In [2]:
## import the pandas library in this cell
import pandas as pd

In [6]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpt.csv", encoding="latin1", engine="python", on_bad_lines="skip")

In [9]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [10]:
## call the last 5 rows

In [11]:
dfbi.tail(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99990,53,57,'NOOKACHAMPS CREEK',48254300.0,122153260.0,2.0,9.0,1977.0,5,2.0,6,7,7,7,N,NaN
99991,53,71,'NINE MILE CANYON',46041500.0,118465600.0,2.0,8.0,1916.0,1,0.0,N,5,5,6,N,NaN
99992,53,63,'LITTLE SPOKANE RIVER',47541420.0,117203676.0,2.0,9.0,1984.0,5,2.0,7,7,7,8,N,NaN
99993,53,77,'ROZA CANAL',46360246.0,120252046.0,2.0,16.0,1967.0,5,2.0,7,7,6,6,N,NaN
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [14]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
95002,53,33,'DEER CREEK',47424013.0,121590331.0,1.0,6.0,1946.0,2,1.0,8,7,7,8,N,NaN
33353,48,287,'MIDDLE YEGUA CREEK',30244881.0,97132124.0,2.0,9.0,1994.0,3,2.0,7,6,6,6,N,NaN
12735,48,135,'DRAW',31551169.0,102201902.0,1.0,14.0,1965.0,1,19.0,N,N,N,8,7,NaN
24027,48,157,'Oyster Creek',29383578.0,95430045.0,2.0,9.0,2015.0,5,2.0,7,8,7,8,N,NaN
52304,48,199,'DRAW',30273852.0,94232030.0,1.0,2.0,1924.0,1,19.0,N,N,N,7,7,NaN
36718,48,29,'LP 1604',29275457.0,98173301.0,1.0,11.0,1962.0,5,2.0,6,7,6,N,N,NaN
11270,48,503,'RATTLESNAKE CREEK',33113820.0,98445589.0,1.0,7.0,1991.0,1,19.0,N,N,N,7,7,1.0
20135,48,183,'RABBIT CREEK RELIEF',32245554.0,94520734.0,1.0,16.0,1935.0,3,2.0,7,6,6,6,N,NaN
49097,48,121,'Prairie Creek',33034720.0,97030069.0,3.0,19.0,1998.0,1,19.0,N,N,N,7,7,NaN
98397,53,37,'N. FORK TEANAWAY RIVER',47213917.0,120512776.0,64.0,9.0,1966.0,7,2.0,7,7,7,8,N,NaN
34274,48,453,'MERRILLTOWN DR',30265781.0,97414515.0,1.0,12.0,2006.0,5,2.0,7,8,7,N,N,NaN
90551,51,700,'Unnamed Stream',37091033.0,76323224.0,4.0,19.0,2020.0,1,19.0,N,N,N,8,8,NaN
46018,48,113,'LP 12 (Buckner Blvd)',32460978.0,96405746.0,1.0,16.0,1977.0,5,2.0,7,7,7,N,N,NaN
94996,53,77,'N FK CLEAR CREEK',46392220.0,121211930.0,1.0,2.0,1946.0,2,4.0,7,7,7,8,N,NaN
40013,48,463,'ROSE DRAW',29261473.0,99453698.0,1.0,6.0,1932.0,1,19.0,N,N,N,7,7,NaN
53473,48,361,'COW BAYOU',30075042.0,93545881.0,1.0,1.0,2009.0,5,2.0,7,7,7,7,N,1.0
85698,51,700,'CSX RAILWAY',37062137.0,76301439.0,4.0,14.0,1981.0,3,2.0,6,6,6,N,N,NaN
71222,49,15,'COTTON WOOD WASH',39123262.0,111012716.0,1.0,2.0,1964.0,5,2.0,7,7,6,5,N,1.0
87982,51,101,'COHOKE MILL PD SPILLWAY',37345365.0,76565303.0,1.0,9.0,1999.0,3,2.0,8,8,8,8,N,NaN
39984,48,463,'COOKS SLOUGH',29121441.0,99480427.0,1.0,14.0,1939.0,2,1.0,6,6,7,7,N,NaN

In [21]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
dfbi.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

In [24]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [25]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
47035,48,113,'HICKORY CREEK TRIB',32394683.0,96355405.0,4.0,19.0,1985.0,5,2.0,7,8,8,7,N,NaN
68898,48,61,'6TH; 7TH & MCDAVITT BLVD',25544639.0,97292528.0,NaN,17.0,2007.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
34309,48,453,'WILBARGER CREEK TRIB',30275014.0,97335131.0,2.0,19.0,2009.0,1,0.0,8,7,7,7,N,NaN
76918,51,13,'FOUR MILE RUN',38520376.0,77074003.0,2.0,16.0,1987.0,3,2.0,6,6,7,7,N,NaN
60981,48,485,'FM 2650',33521829.0,98354627.0,NaN,7.0,2009.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
49775,48,139,'WAXAHACHIE CREEK',32195386.0,96461936.0,2.0,9.0,2010.0,3,2.0,7,6,6,6,N,NaN
11993,48,381,'Draw',34585111.0,102003482.0,1.0,2.0,1931.0,1,19.0,N,N,N,7,6,NaN
95209,53,61,'SR 529/E MARINE VIEW DR',48004050.0,122112550.0,1.0,12.0,1955.0,1,1.0,7,7,7,N,N,NaN
1272,47,37,'GAY ST.',36100493.0,86463959.0,NaN,19.0,1951.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
10803,48,485,'SH 240 (156-12)',33544600.0,98290203.0,1.0,14.0,1979.0,5,2.0,7,7,6,N,N,NaN

In [27]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [33]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [34]:
## call FEATURES_DESC_006A as a series using square bracket notation
dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [36]:
## what are the unique owner codes?
dfbi["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

In [37]:
## WHAT DO THESE CODES MEAN

In [ ]:
These codes are numbers that link the bridge to the area/entity that is reponsible for the bridges for inspection purposes.